rscomponents.test:
  url: https://uk.rs-online.com
  searchTestDataFile: SearchFilterTestData.csv
  endToEndTestDataFile: EndToEndTestData.csv
  userName: putYourUserName
  password: putYourPassword
rscomponents.system:
  selectedBrowser: chrome
  browserFolder: browserdrivers

