rscomponents.test:
  url: https://uk.rs-online.com
  searchTestDataFile: SearchFilterTestData.csv
  endToEndTestDataFile: EndToEndTestData.csv
  userName: EnterYourUserName
  password: EnterYourPassword
rscomponents.system:
  selectedBrowser: chrome
  browserFolder: browserdrivers

